#PROBLEMATICA 1: SELECTOR DE BICICLETA

'''
NECESITAMOS ESCOGER LA MEJOR DE 5 BICICLETAS TENEMOS DATOS DE EFICIENCIA, ESTABILIDAD Y MODELO DE CADA UNA DE ELLAS Y UNA ECUACIÓN
DE VALORACIÓN PARA INGRESAR A LA SOLUCIÓN NECESITAMOS IMPLEMENTAR UN SISTEMA DE AUTENTICACIÓN DE USUARIOS
'''
